apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: LW4gJ2FkbWluJyANCg==
  mongo-root-password: LW4gJ2FkbWluQDEyMycgDQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              key: mongodb-secret
              value: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASWORD
          valueFrom: 
            secretKeyRef:
              key: mongodb-secret
              value: mongo-root-password